language: node_js
node_js:
- 8.9.4
branches:
  only:
  - master
before_install:
- npm install -g typescript ts-node
- npm run setup
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: iIHYee9JW0ayDlQXJgtAZkaiYKoFFPjy6RBARX0kBsaIFZ3gmbyibm2RPc87Mznl67XU/Xc0q36ayo+t3sAVZUGY/83ZWIenu3bsvdq4/Kw+5KulWOOU476weTvb9wnvfvk4QVPT/48ulMGhZgfKk/lsq3n3G0v0yUfkVGuPa/XbH2AsitSjbAThhsuO8G/Wo6t5T1ylMUKTl3Rpw+XPZhvWO+eYxzWzehFpd1HFeVqVAN5DjoYnHH+hduxtTN89q0hTgXpGFikPQbuczSXgP2jCQML84//a/qYV0nbfXXrlJ5q4CqhpCAzqRJ0e934KVgcm/6cEoPpkPCFbzaEdQCVRZWow9hSCiOZ3Y9QIQifwdFtIhv+KHS0XTT+L8CgLVH/MBFkWDOZb8BvRszk62tcRWXfyiH4aaF77jqOQIt/7J8KPAIBb850Cz8sSPM7gCBb7PZX5d/1uXbFxgazEJOlo2gl6NYI8mM0ywwSobNCYekjKzjGmjVfUqwI/UM188MyNvcLhCTZkWq1C2W0maGUcEorEScQB0+Bvs6QAvbLnxzivAqMiyUMqGpwF4huvhzK42gIjzX2s0a5GKw9broErGJ7AisIX0h42eDE807+vNu6XEi0t10xdNtkZrPq/dbYDOkIr17545k1O4m41rfKhIBKNiOeXO51jlaf6vZY=
  skip_cleanup: true
  app: react-express-typed
